services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pympp-backend
    ports:
      - "28000:28000"
    restart: unless-stopped
    environment:
      - PYMPP_TYPE=${PYMPP_TYPE:-prod}
      - AUTH_TOKEN=${AUTH_TOKEN:-iamxxk}

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: pympp-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - PYMPP_TYPE=${PYMPP_TYPE:-prod}