"""
Quiz API endpoints
Provides backend API interfaces for Quiz functionality
"""
from fastapi import APIRouter, HTTPException, Depends, Header
from typing import Optional, List
from datetime import datetime

from ..db import get_repository, QuizRepository
from ..db.models import QuizSession as QuizSessionModel
from ..db.models import QuizRecord as QuizRecordModel
from .schema import (
    QuizStartRequest, QuizStartResponse,
    QuizAnswerRequest, QuizAnswerResponse,
    QuizEndRequest, QuizSessionSummary,
    QuizRecordItem, QuizHistoryResponse,
    QuizStatsResponse
)
from ..log import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/quiz", tags=["quiz"])


def get_quiz_repo() -> QuizRepository:
    """Get Quiz repository instance"""
    return get_repository()


def get_session_id(x_session_id: Optional[str] = Header(None, alias="X-Session-ID")) -> str:
    """Get user session ID"""
    if not x_session_id:
        raise HTTPException(status_code=400, detail="Session ID is required")
    return x_session_id


@router.post("/start", response_model=QuizStartResponse)
def start_quiz(
    req: QuizStartRequest,
    session_id: str = Depends(get_session_id),
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """Start a new Quiz session"""
    quiz_session = QuizSessionModel(
        id="",  # Generated by repository
        session_id=session_id,
        total_questions=req.total_questions,
    )

    quiz_session_id = repo.create_session(quiz_session)
    session = repo.get_session(quiz_session_id)

    logger.info(f"Started quiz session {quiz_session_id} for user {session_id}")

    return QuizStartResponse(
        quiz_session_id=quiz_session_id,
        started_at=session.started_at or datetime.now()
    )


@router.post("/record_answer", response_model=QuizAnswerResponse)
def record_answer(
    req: QuizAnswerRequest,
    session_id: str = Depends(get_session_id),
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """Record a single answer"""
    # Verify quiz session exists
    quiz_session = repo.get_session(req.quiz_session_id)
    if quiz_session is None:
        raise HTTPException(status_code=404, detail="Quiz session not found")

    # Verify session_id matches
    if quiz_session.session_id != session_id:
        raise HTTPException(status_code=403, detail="Quiz session does not belong to this user")

    record = QuizRecordModel(
        quiz_session_id=req.quiz_session_id,
        session_id=session_id,
        instruction_name=req.instruction_name,
        question_index=req.question_index,
        user_tuse_rs=req.user_tuse_rs,
        user_tuse_rt=req.user_tuse_rt,
        user_tnew=req.user_tnew,
        correct_tuse_rs=req.correct_tuse_rs,
        correct_tuse_rt=req.correct_tuse_rt,
        correct_tnew=req.correct_tnew,
        is_correct=req.is_correct,
    )

    record_id = repo.save_record(record)

    logger.info(f"Recorded answer for {req.instruction_name}: correct={req.is_correct}")

    return QuizAnswerResponse(
        record_id=record_id,
        success=True
    )


@router.post("/end", response_model=QuizSessionSummary)
def end_quiz(
    req: QuizEndRequest,
    session_id: str = Depends(get_session_id),
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """End Quiz session"""
    # Verify quiz session exists
    quiz_session = repo.get_session(req.quiz_session_id)
    if quiz_session is None:
        raise HTTPException(status_code=404, detail="Quiz session not found")

    # Verify session_id matches
    if quiz_session.session_id != session_id:
        raise HTTPException(status_code=403, detail="Quiz session does not belong to this user")

    # Update session
    updated_session = repo.end_session(req.quiz_session_id, req.correct_count)

    logger.info(f"Ended quiz session {req.quiz_session_id}: score={req.correct_count}/{quiz_session.total_questions}")

    return QuizSessionSummary(
        quiz_session_id=req.quiz_session_id,
        total_questions=updated_session.total_questions,
        correct_count=updated_session.correct_count,
        started_at=updated_session.started_at,
        ended_at=updated_session.ended_at
    )


@router.get("/history", response_model=QuizHistoryResponse)
def get_history(
    session_id: str = Depends(get_session_id),
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """Get user's Quiz history"""
    sessions = repo.get_sessions_by_user(session_id)

    # Get recent answer records
    records = repo.get_records_by_user(session_id, limit=100)

    session_summaries = [
        QuizSessionSummary(
            quiz_session_id=s.id,
            total_questions=s.total_questions,
            correct_count=s.correct_count,
            started_at=s.started_at,
            ended_at=s.ended_at
        )
        for s in sessions
    ]

    record_items = [
        QuizRecordItem(
            id=r.id,
            instruction_name=r.instruction_name,
            question_index=r.question_index,
            user_tuse_rs=r.user_tuse_rs,
            user_tuse_rt=r.user_tuse_rt,
            user_tnew=r.user_tnew,
            correct_tuse_rs=r.correct_tuse_rs,
            correct_tuse_rt=r.correct_tuse_rt,
            correct_tnew=r.correct_tnew,
            is_correct=r.is_correct,
            created_at=r.created_at
        )
        for r in records
    ]

    return QuizHistoryResponse(
        sessions=session_summaries,
        records=record_items
    )


@router.get("/stats", response_model=QuizStatsResponse)
def get_stats(
    session_id: str = Depends(get_session_id),
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """Get user's Quiz statistics"""
    stats = repo.get_stats_by_user(session_id)

    return QuizStatsResponse(
        total_sessions=stats['total_sessions'],
        total_questions=stats['total_questions'],
        correct_count=stats['correct_count'],
        accuracy_rate=stats['accuracy_rate'],
        most_wrong_instructions=stats['most_wrong_instructions']
    )


# === Admin APIs (for viewing all students' data) ===

@router.get("/admin/sessions")
def get_all_sessions(
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """
    Get all quiz sessions (admin view)
    Returns list of all sessions with session_id and actual stats
    """
    sessions = repo.get_all_sessions()
    result = []
    for s in sessions:
        # Get actual answered count for this session
        records = repo.get_records_by_quiz_session(s.id)
        actual_answered = len(records)

        result.append({
            "quiz_session_id": s.id,
            "session_id": s.session_id,
            "total_questions": s.total_questions,
            "actual_answered": actual_answered,
            "correct_count": s.correct_count,
            "started_at": s.started_at,
            "ended_at": s.ended_at,
        })
    return result


@router.get("/admin/stats", response_model=QuizStatsResponse)
def get_global_stats(
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """Get global statistics for all students"""
    stats = repo.get_global_stats()
    return QuizStatsResponse(
        total_sessions=stats['total_sessions'],
        total_questions=stats['total_questions'],
        correct_count=stats['correct_count'],
        accuracy_rate=stats['accuracy_rate'],
        most_wrong_instructions=stats['most_wrong_instructions'],
    )


@router.get("/admin/records")
def get_all_records(
    limit: int = 100,
    repo: QuizRepository = Depends(get_quiz_repo)
):
    """Get all answer records (admin view)"""
    records = repo.get_all_records(limit)
    return [
        QuizRecordItem(
            id=r.id,
            instruction_name=r.instruction_name,
            question_index=r.question_index,
            user_tuse_rs=r.user_tuse_rs,
            user_tuse_rt=r.user_tuse_rt,
            user_tnew=r.user_tnew,
            correct_tuse_rs=r.correct_tuse_rs,
            correct_tuse_rt=r.correct_tuse_rt,
            correct_tnew=r.correct_tnew,
            is_correct=r.is_correct,
            created_at=r.created_at,
        )
        for r in records
    ]