"""
Quiz data model definitions
Uses dataclass for data structures, easy to extend later
"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class QuizSession:
    """Quiz session record"""
    id: str                              # UUID
    session_id: str                      # User session ID
    total_questions: int                 # Total number of questions
    correct_count: int = 0               # Number of correct answers
    started_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None
    created_at: Optional[datetime] = None


@dataclass
class QuizRecord:
    """Single answer record"""
    quiz_session_id: str                 # Quiz session ID
    session_id: str                      # User session ID
    instruction_name: str                # Instruction name
    question_index: int                  # Question index
    user_tuse_rs: Optional[int] = None   # User answer: null='-', -99='UNKNOWN'
    user_tuse_rt: Optional[int] = None
    user_tnew: Optional[int] = None
    correct_tuse_rs: str = ""            # Correct answer
    correct_tuse_rt: str = ""
    correct_tnew: str = ""
    is_correct: bool = False             # Whether all correct
    id: Optional[int] = None             # Record ID (generated by database)
    created_at: Optional[datetime] = None